name: Deploy Web

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'

jobs:
  deploy_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: cd web && npm install
      - name: Build Web
        run: cd web && npm run build
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JUSTRED }}"
          channelId: live
          projectId: justred-project
          entryPoint: "./web"
